#!/usr/bin/env python3
"""Operational enums aligned with decision/rebalance logic."""

from enum import Enum


class FinalStance(Enum):
    """Final investment stance."""
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"
    HOLD = "HOLD"


class ReasonCode(Enum):
    """Reason codes used across decision and hold-policy modules."""
    BULL_REGIME_HIGH_CONF = "BULL_REGIME_HIGH_CONFIDENCE"
    BULL_REGIME_CONSENSUS = "BULL_REGIME_WITH_CONSENSUS"
    LOW_RISK_BULL = "LOW_RISK_BULLISH_ENVIRONMENT"

    BEAR_REGIME_HIGH_CONF = "BEAR_REGIME_HIGH_CONFIDENCE"
    BEAR_REGIME_CONSENSUS = "BEAR_REGIME_WITH_CONSENSUS"
    HIGH_RISK_BEAR = "HIGH_RISK_BEARISH_ENVIRONMENT"

    NEUTRAL_REGIME = "NEUTRAL_REGIME"
    MIXED_SIGNALS = "MIXED_SIGNALS"

    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    AGENT_CONFLICT = "AGENT_CONFLICT_UNRESOLVED"
    DATA_QUALITY_ISSUE = "DATA_QUALITY_ISSUE"
    CONSTRAINT_VIOLATION_UNREPAIRED = "CONSTRAINT_VIOLATION_UNREPAIRED"
    REGIME_STANCE_MISMATCH = "REGIME_STANCE_MISMATCH"
    CLIENT_PROFILE_MISSING = "CLIENT_PROFILE_MISSING"
    DEFAULT_HOLD = "DEFAULT_HOLD"


class TriggerType(Enum):
    """Rebalancing trigger categories."""
    DRIFT = "DRIFT"
    REGIME_CHANGE = "REGIME_CHANGE"
    CONSTRAINT_REPAIR = "CONSTRAINT_REPAIR"
    SCHEDULED = "SCHEDULED"
    MANUAL = "MANUAL"


class SignalType(Enum):
    """Signal hierarchy marker."""
    CORE = "CORE"
    AUXILIARY = "AUXILIARY"
