"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Download,
  FileJson,
  FileText,
  FileSpreadsheet,
  CheckCircle,
  Loader2,
  X,
} from "lucide-react";
import type { EIMASAnalysis } from "@/lib/types";

interface ExportReportDialogProps {
  data?: EIMASAnalysis;
  onClose?: () => void;
}

type ExportFormat = "json" | "markdown" | "csv";

export function ExportReportDialog({ data, onClose }: ExportReportDialogProps) {
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat>("json");
  const [exporting, setExporting] = useState(false);
  const [exported, setExported] = useState(false);

  if (!data) {
    return (
      <Card className="bg-[#0d1117] border-[#30363d]">
        <CardContent className="p-8 text-center text-gray-400">
          <FileText className="w-12 h-12 mx-auto mb-4 text-gray-600" />
          <p>No data available for export</p>
        </CardContent>
      </Card>
    );
  }

  const formats = [
    {
      id: "json" as const,
      name: "JSON",
      icon: FileJson,
      description: "Complete analysis data in JSON format",
      extension: "json",
    },
    {
      id: "markdown" as const,
      name: "Markdown",
      icon: FileText,
      description: "Formatted report for documentation",
      extension: "md",
    },
    {
      id: "csv" as const,
      name: "CSV",
      icon: FileSpreadsheet,
      description: "Tabular data for spreadsheet analysis",
      extension: "csv",
    },
  ];

  const generateJSON = () => {
    return JSON.stringify(data, null, 2);
  };

  const generateMarkdown = () => {
    let md = `# EIMAS Analysis Report\n\n`;
    md += `**Generated:** ${data.timestamp}\n\n`;
    md += `## Executive Summary\n\n`;
    md += `- **Final Recommendation:** ${data.final_recommendation}\n`;
    md += `- **Confidence:** ${(data.confidence * 100).toFixed(0)}%\n`;
    md += `- **Risk Level:** ${data.risk_level}\n`;
    md += `- **Risk Score:** ${data.risk_score.toFixed(2)}\n\n`;

    md += `## Market Regime\n\n`;
    md += `- **Regime:** ${data.regime.regime}\n`;
    md += `- **Trend:** ${data.regime.trend}\n`;
    md += `- **Volatility:** ${data.regime.volatility}\n`;
    md += `- **Confidence:** ${(data.regime.confidence * 100).toFixed(0)}%\n\n`;

    if (data.reasoning_chain && data.reasoning_chain.length > 0) {
      md += `## Reasoning Chain\n\n`;
      data.reasoning_chain.forEach((step, i) => {
        md += `### Step ${i + 1}: ${step.agent}\n\n`;
        md += `${step.output_summary}\n\n`;
        md += `**Confidence:** ${step.confidence}%\n\n`;
        if (step.key_factors && step.key_factors.length > 0) {
          md += `**Key Factors:**\n`;
          step.key_factors.forEach((factor) => {
            md += `- ${factor}\n`;
          });
          md += `\n`;
        }
      });
    }

    if (data.portfolio_weights) {
      md += `## Portfolio Allocation\n\n`;
      Object.entries(data.portfolio_weights)
        .sort(([, a], [, b]) => b - a)
        .forEach(([ticker, weight]) => {
          md += `- **${ticker}:** ${(weight * 100).toFixed(2)}%\n`;
        });
      md += `\n`;
    }

    md += `## AI Consensus\n\n`;
    md += `- **Full Mode:** ${data.full_mode_position}\n`;
    md += `- **Reference Mode:** ${data.reference_mode_position}\n`;
    md += `- **Modes Agree:** ${data.modes_agree ? "Yes" : "No"}\n\n`;

    if (data.warnings && data.warnings.length > 0) {
      md += `## Warnings\n\n`;
      data.warnings.forEach((warning) => {
        md += `- ${warning}\n`;
      });
      md += `\n`;
    }

    md += `---\n*Generated by EIMAS v2.1.1*\n`;

    return md;
  };

  const generateCSV = () => {
    let csv = "Metric,Value\n";
    csv += `Timestamp,${data.timestamp}\n`;
    csv += `Final Recommendation,${data.final_recommendation}\n`;
    csv += `Confidence,${(data.confidence * 100).toFixed(2)}%\n`;
    csv += `Risk Level,${data.risk_level}\n`;
    csv += `Risk Score,${data.risk_score.toFixed(2)}\n`;
    csv += `Market Regime,${data.regime.regime}\n`;
    csv += `Trend,${data.regime.trend}\n`;
    csv += `Volatility,${data.regime.volatility}\n`;
    csv += `Full Mode Position,${data.full_mode_position}\n`;
    csv += `Reference Mode Position,${data.reference_mode_position}\n`;
    csv += `Modes Agree,${data.modes_agree}\n\n`;

    if (data.portfolio_weights) {
      csv += `\nPortfolio Allocation\n`;
      csv += `Ticker,Weight %\n`;
      Object.entries(data.portfolio_weights)
        .sort(([, a], [, b]) => b - a)
        .forEach(([ticker, weight]) => {
          csv += `${ticker},${(weight * 100).toFixed(2)}\n`;
        });
    }

    return csv;
  };

  const handleExport = () => {
    setExporting(true);

    setTimeout(() => {
      let content = "";
      let filename = `eimas-report-${data.timestamp}`;

      switch (selectedFormat) {
        case "json":
          content = generateJSON();
          filename += ".json";
          break;
        case "markdown":
          content = generateMarkdown();
          filename += ".md";
          break;
        case "csv":
          content = generateCSV();
          filename += ".csv";
          break;
      }

      const blob = new Blob([content], {
        type: selectedFormat === "json" ? "application/json" : "text/plain",
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);

      setExporting(false);
      setExported(true);

      setTimeout(() => {
        setExported(false);
        onClose?.();
      }, 2000);
    }, 500);
  };

  return (
    <Card className="bg-[#0d1117] border-[#30363d]">
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-white flex items-center gap-2">
            <Download className="w-5 h-5" />
            Export Analysis Report
          </CardTitle>
          {onClose && (
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-white transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          )}
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        <div>
          <p className="text-sm text-gray-400 mb-4">
            Select the format for exporting your EIMAS analysis report
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {formats.map((format) => {
              const Icon = format.icon;
              const isSelected = selectedFormat === format.id;

              return (
                <button
                  key={format.id}
                  onClick={() => setSelectedFormat(format.id)}
                  className={`p-4 rounded-lg border-2 transition-all text-left ${
                    isSelected
                      ? "border-[#238636] bg-[#238636]/10"
                      : "border-[#30363d] hover:border-gray-600"
                  }`}
                >
                  <div className="flex items-center gap-3 mb-2">
                    <Icon
                      className={`w-6 h-6 ${
                        isSelected ? "text-[#238636]" : "text-gray-400"
                      }`}
                    />
                    <span className="font-semibold text-white">{format.name}</span>
                    {isSelected && <CheckCircle className="w-4 h-4 text-[#238636] ml-auto" />}
                  </div>
                  <p className="text-xs text-gray-400">{format.description}</p>
                </button>
              );
            })}
          </div>
        </div>

        <div className="bg-[#161b22] rounded-lg p-4 border border-[#30363d]">
          <h4 className="text-sm font-semibold text-gray-300 mb-3">Export Contents:</h4>
          <ul className="space-y-2 text-sm text-gray-400">
            <li className="flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-green-400" />
              Executive summary and key metrics
            </li>
            <li className="flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-green-400" />
              Market regime analysis
            </li>
            <li className="flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-green-400" />
              Portfolio allocation recommendations
            </li>
            <li className="flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-green-400" />
              AI reasoning chain {selectedFormat === "csv" && "(summary only)"}
            </li>
            <li className="flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-green-400" />
              Risk assessment and warnings
            </li>
          </ul>
        </div>

        <div className="flex items-center gap-3">
          <Button
            onClick={handleExport}
            disabled={exporting || exported}
            className="flex-1 bg-[#238636] hover:bg-[#2ea043] text-white"
          >
            {exporting ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Exporting...
              </>
            ) : exported ? (
              <>
                <CheckCircle className="w-4 h-4 mr-2" />
                Exported!
              </>
            ) : (
              <>
                <Download className="w-4 h-4 mr-2" />
                Export as {formats.find((f) => f.id === selectedFormat)?.name}
              </>
            )}
          </Button>
          {onClose && (
            <Button
              variant="outline"
              onClick={onClose}
              className="bg-[#161b22] border-[#30363d] text-gray-300 hover:bg-gray-800"
            >
              Cancel
            </Button>
          )}
        </div>

        <div className="text-xs text-gray-500 text-center">
          File will be saved as: eimas-report-{data.timestamp}.{formats.find((f) => f.id === selectedFormat)?.extension}
        </div>
      </CardContent>
    </Card>
  );
}
